name: garbage
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=24.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - scipy=1.10.0
  - tqdm
  - pip:
    - webdataset==0.2.5
    - torchmetrics==0.6.0
    - matplotlib
    - termcolor
    - pillow
    - git+https://github.com/openai/CLIP.git
    - annotated-types==0.7.0
    - anyio==4.6.0
    - blinker==1.8.2
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - click==8.1.7
    - distro==1.9.0
    - filelock==3.16.1
    - Flask==3.0.3
    - Flask-Cors==5.0.0
    - Flask-SQLAlchemy==3.1.1
    - fsspec==2024.9.0
    - ftfy==6.2.3
    - greenlet==3.1.0
    - h11==0.14.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.25.1
    - idna==3.10
    - itsdangerous==2.2.0
    - Jinja2==3.1.4
    - jiter==0.5.0
    - MarkupSafe==2.1.5
    - mpmath==1.3.0
    - networkx==3.3
    - numpy==2.1.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.77
    - nvidia-nvtx-cu12==12.1.105
    - open_clip_torch==2.26.1
    - openai==1.50.2
    - packaging==24.1
    - pillow==10.4.0
    - psycopg2-binary==2.9.9
    - pydantic==2.9.2
    - pydantic_core==2.23.4
    - python-dotenv==1.0.1
    - PyYAML==6.0.2
    - regex==2024.9.11
    - requests==2.32.3
    - safetensors==0.4.5
    - sniffio==1.3.1
    - SQLAlchemy==2.0.35
    - sympy==1.13.3
    - timm==1.0.9
    - torch==2.4.1
    - torchvision==0.19.1
    - tqdm==4.66.5
    - triton==3.0.0
    - typing_extensions==4.12.2
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - Werkzeug==3.0.4
    - -e .
